### ISSUE TITLE
Make `category` values arrays?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/gazetteer#16]
In v2, we added a `category` key. Some places though fall under multiple categories (e.g. if a place was chosen to represent the interaction between a park and a tunnel, it should probably be categorized as both `landuse` and `tunnel`). Would it make sense to use array values for this key rather than single strings?

@dasulit

**Comment by dasulit** [comment]
I'm hesitant about using arrays for categories because it might result in a redundancy between categories and tags. I think this might be telling of the fatal flaw of the `category` solution, which this time around I'm not feeling as confident on 😬 

What do you think of the idea that categories apply to tags, not places? In the data, that could mean we go all in on separators (`road:main` `barrier:hedge`), and remove categories as a separate key.

**Comment by nickidlugash** [comment]
superseded by https://github.com/mapbox/gazetteer/issues/17
