### ISSUE TITLE
Should lint-gazetteer be exported?

### ISSUE THREAD

**Issue by tristen** [mapbox/gazetteer#41]
Exporting [lint-gazetteer](https://github.com/mapbox/gazetteer/blob/master/lib/lint-gazetteer.js) means a few packages (@mapbox/geojsonhint, json-lint) are added as dependencies when gazetteer is installed. The drawback is when you just want to use gazetteer for place data, you get a bunch more stuff.

@dasulit do you know the backstory here? I did a quick organization search for its use and I don't see it used anywhere. If it's necessary, maybe we could set it up as its own `gazetteer-lint` package that tests [here require](https://github.com/mapbox/gazetteer/blob/master/test.js#L5).

**Comment by dasulit** [comment]
Carto-cam should be using this (though is not yet), so we should export lint-gazetteer 👍

**Comment by tristen** [comment]
@dasulit oh yes! cool. Any objection to creating a separate package/repo for this and leaving this project to just export place data?

cc/ @mourner

**Comment by dasulit** [comment]
Hm, exporting as a separate package does seem a bit odd to me since the source of truth for the gazetteer spec lives here, ideally that spec and this linter would come together. I'm open to going that route if this is an immediate blocker to you, though.

As an alternate suggestion, can we not run geojsonhint/json-lint in `lint-gazetteer`, and just have checking for valid json/geojson be the responsibility of the consumer?

**Comment by tristen** [comment]
> As an alternate suggestion, can we not run geojsonhint/json-lint in lint-gazetteer, and just have checking for valid json/geojson be the responsibility of the consumer?

Ah yeah, that's a good suggestion. Let's do that 👍
